"""Export and import procedure aliases for chat-based generation.

Two subcommands:
  export: Write procedures needing aliases to a JSON file for the chat to read.
  import: Upsert aliases generated by the chat back into Supabase.

Usage:
    python scripts/procedure_aliases.py export --out analysis/procedures_to_alias.json
    python scripts/procedure_aliases.py export --active-only
    python scripts/procedure_aliases.py import --in analysis/procedure_aliases_generated.json
    python scripts/procedure_aliases.py import --in analysis/procedure_aliases_generated.json --dry-run
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from dotenv import dotenv_values
from supabase import create_client

VALID_TYPES = {"acronym", "short_name", "informal", "package"}


def _get_client():
    env = dotenv_values(Path(__file__).parent.parent / ".env")
    return create_client(env["SUPABASE_URL"], env["SUPABASE_SERVICE_ROLE_KEY"])


def _paginate(client, table, select, filters=None):
    rows = []
    offset = 0
    while True:
        q = client.table(table).select(select).range(offset, offset + 999)
        if filters:
            for method, args in filters:
                q = getattr(q, method)(*args)
        batch = (q.execute()).data or []
        rows.extend(batch)
        if len(batch) < 1000:
            break
        offset += 1000
    return rows


def cmd_export(args) -> None:
    client = _get_client()

    already: set[str] = set()
    if not args.include_aliased:
        for r in _paginate(client, "procedure_aliases", "procedure_id"):
            already.add(r["procedure_id"])
        print(f"Skipping {len(already)} procedures that already have aliases")

    active_ids: set[str] | None = None
    if args.active_only:
        active_ids = set()
        for r in _paginate(
            client, "lobbying_meetings", "related_procedure",
            [("not_.is_", ("related_procedure", "null")), ("neq", ("related_procedure", ""))],
        ):
            if r.get("related_procedure"):
                active_ids.add(r["related_procedure"])
        print(f"Active procedures referenced in lobbying_meetings: {len(active_ids)}")

    procedures = []
    for p in _paginate(client, "procedures", "id,title,procedure_type,subjects"):
        if p["id"] in already:
            continue
        if active_ids is not None and p["id"] not in active_ids:
            continue
        procedures.append({
            "id": p["id"],
            "title": (p.get("title") or "").strip(),
            "procedure_type": p.get("procedure_type"),
            "subjects": (p.get("subjects") or [])[:5],
        })

    if args.limit:
        procedures = procedures[: args.limit]

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(procedures, indent=2, ensure_ascii=False))
    print(f"Wrote {len(procedures)} procedures to {out_path}")


def cmd_import(args) -> None:
    in_path = Path(args.in_path)
    if not in_path.exists():
        raise SystemExit(f"No such file: {in_path}")

    raw = json.loads(in_path.read_text())
    if not isinstance(raw, list):
        raise SystemExit("Expected a JSON array at the top level")

    rows: list[dict] = []
    skipped_no_id = 0
    skipped_empty = 0
    normalized_types = 0
    for entry in raw:
        proc_id = (entry.get("id") or "").strip()
        if not proc_id:
            skipped_no_id += 1
            continue
        aliases = entry.get("aliases") or []
        if not aliases:
            skipped_empty += 1
            continue
        for a in aliases:
            alias_text = (a.get("alias") or "").strip()
            alias_type = (a.get("type") or "informal").strip()
            if alias_type not in VALID_TYPES:
                normalized_types += 1
                alias_type = "informal"
            if not alias_text:
                continue
            rows.append({
                "procedure_id": proc_id,
                "alias": alias_text,
                "alias_type": alias_type,
            })

    print(
        f"Parsed {len(rows)} aliases across {len(raw) - skipped_no_id - skipped_empty} procedures "
        f"(skipped {skipped_no_id} without id, {skipped_empty} with no aliases, "
        f"normalized {normalized_types} unknown types to 'informal')"
    )

    if args.dry_run:
        for r in rows[:20]:
            print(f"  {r['procedure_id']} -> {r['alias']} ({r['alias_type']})")
        if len(rows) > 20:
            print(f"  ... and {len(rows) - 20} more")
        return

    client = _get_client()
    inserted = 0
    for i in range(0, len(rows), 500):
        batch = rows[i : i + 500]
        client.table("procedure_aliases").upsert(
            batch, on_conflict="alias,procedure_id"
        ).execute()
        inserted += len(batch)
        print(f"  Upserted {inserted}/{len(rows)}")

    print(f"Done. Upserted {inserted} aliases into procedure_aliases.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export/import procedure aliases")
    sub = parser.add_subparsers(dest="command", required=True)

    exp = sub.add_parser("export", help="Export procedures needing aliases")
    exp.add_argument("--out", default="analysis/procedures_to_alias.json")
    exp.add_argument("--limit", type=int, default=None)
    exp.add_argument("--active-only", action="store_true")
    exp.add_argument("--include-aliased", action="store_true")

    imp = sub.add_parser("import", help="Import generated aliases")
    imp.add_argument("--in", dest="in_path", default="analysis/procedure_aliases_generated.json")
    imp.add_argument("--dry-run", action="store_true")

    args = parser.parse_args()
    if args.command == "export":
        cmd_export(args)
    else:
        cmd_import(args)


if __name__ == "__main__":
    main()
